### ISSUE TITLE
Working or not ?

### ISSUE THREAD

**Issue by ychoucha** [tuxmouraille/tvheadend_ynh#1]
Hello, i have tryed on yunohst 2.4, but not working
![502 bad gateway - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/15688843/fdd34070-2773-11e6-98e4-533473a26bea.jpg)

can u knwo what is wrong please ?

**Comment by tuxmouraille** [comment]
Hello,
This is a work in progress.

**Comment by ychoucha** [comment]
OK

I installés it on m'y production serveur ans notre working

**Comment by tuxmouraille** [comment]
Salut,
Je viens de mettre à jour les scripts, j'ai testé l'installation dans une VM fraiche.
Pouvez vous me dire si ça fonctionne chez vous?

**Comment by ychoucha** [comment]
Bonjour,

ça ne fonctionne toujours pas, j'ai toujours droit au message : 

502 Bad Gateway
nginx

**Comment by ychoucha** [comment]
J'avance, mais je suis toujours pas arrivé !!

du coup j'ai installé tvheadend via un sudo apt-get install tvheadend
et j'arrive à avoir une page de login mot de passe mais impossible de ce connecter : 

![tvheadendlogin](https://cloud.githubusercontent.com/assets/301074/15719452/e8df5154-2827-11e6-8603-87ac75c4c8a3.jpg)

et aprés je me retrouve sur la page : 

401 Unauthorized

Default Login

j'ai même essayer un 
sudo dpkg-reconfigure tvheadend

et mis des login password différent mais impossible de me connecter sur l'interface web


j'y suis presque manque pas grand chose :/

**Comment by tuxmouraille** [comment]
Je vous propose de tout désinstaller:

sudo yunohost app remove tvheadend
sudo apt-get autoremove tvheadend --purge
sudo rm -f /etc/apt/source.list.d/tvheadend.list
sudo rm -f /home/hts/.hts/tvheadend/superuser
sudo apt-get clean
sudo apt-get autoclean

Puis réinstallation:
sudo yunohost app install https://github.com/tuxmouraille/tvheadend_ynh

J'ai ajouté le choix pour le nom de l'administrateur de Tvheadend et son mot de passe.

**Comment by ychoucha** [comment]
Merci, mais toujours même probleme : 502 bad gateway :

Voici tout les logs dont je dispose : 


`
pi@raspberrypi:~ $ sudo yunohost app remove tvheadend
Warning: rm: cannot remove ‘/home/hts/.hts/tvheadend/superuser’: No such file or directory
Success! tvheadend successfully removed
Success! SSOwat configuration successfully generated
pi@raspberrypi:~ $ sudo apt-get autoremove tvheadend --purge
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'tvheadend' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
pi@raspberrypi:~ $ sudo rm -f /etc/apt/source.list.d/tvheadend.list
pi@raspberrypi:~ $ sudo rm -f /home/hts/.hts/tvheadend/superuser
pi@raspberrypi:~ $ sudo apt-get clean
pi@raspberrypi:~ $ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree
Reading state information... Done
pi@raspberrypi:~ $ sudo yunohost app install https://github.com/tuxmouraille/tvheadend_ynh
Choose a domain for Tvheadend: monDomaine.com
Choose a path for Tvheadend (default: /tvheadend):
Admin login (default: admin):
Admin password: motDePasse
Warning: gpg: requesting key D401AB61 from hkp server keyserver.ubuntu.com
Warning: gpg: key D401AB61: "Bintray (by JFrog) <bintray@bintray.com>" not changed
Warning: gpg: Total number processed: 1
Warning: gpg:              unchanged: 1
Warning: W: GPG error: http://apt.tvheadend.org jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B42317285E12C7CF
Warning: E: There are problems and -y was used without --force-yes
Warning: cp: cannot create regular file ‘/home/hts/.hts/tvheadend/superuser’: No such file or directory
Warning: Warning: Unit file of tvheadend.service changed on disk, 'systemctl daemon-reload' recommended.
Warning: Job for tvheadend.service failed. See 'systemctl status tvheadend.service' and 'journalctl -xn' for details.
Success! SSOwat configuration successfully generated
Success! Installation complete
`
j'ajoute bien mon utilisateur dans l'interface admin, mais aprés j'ai cette page : 

![502 bad gateway - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/15721706/16d53998-2832-11e6-9246-c88e46e30449.jpg)

**Comment by ychoucha** [comment]
youuuu ça marche, j'ai enfin accés à l'interface web :

voici toute les commandes que j'ai réalisé : 

plus visible sur pastebin : http://pastebin.com/ugTBtPkF

`
pi@raspberrypi:~ $ gpg --keyserver pgpkeys.mit.edu --recv-key  B42317285E12C7CF
gpg: directory `/home/pi/.gnupg' created
gpg: new configuration file `/home/pi/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/pi/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/pi/.gnupg/secring.gpg' created
gpg: keyring `/home/pi/.gnupg/pubring.gpg' created
gpg: requesting key 5E12C7CF from hkp server pgpkeys.mit.edu
gpg: /home/pi/.gnupg/trustdb.gpg: trustdb created
gpg: key 5E12C7CF: public key "Tvheadend (Package Signing Key) <apt@tvheadend.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
pi@raspberrypi:~ $ gpg -a --export B42317285E12C7CF | sudo apt-key add -
OK
pi@raspberrypi:~ $ sudo yunohost app install https://github.com/tuxmouraille/tvheadend_ynh^C
pi@raspberrypi:~ $ sudo yunohost app remove tvheadend
Warning: rm: cannot remove ‘/home/hts/.hts/tvheadend/superuser’: No such file or directory
Success! tvheadend successfully removed
Success! SSOwat configuration successfully generated
pi@raspberrypi:~ $ sudo apt-get autoremove tvheadend --purge
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package 'tvheadend' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
pi@raspberrypi:~ $ sudo rm -f /etc/apt/source.list.d/tvheadend.list
pi@raspberrypi:~ $ sudo rm -f /home/hts/.hts/tvheadend/superuser
pi@raspberrypi:~ $ sudo apt-get clean
pi@raspberrypi:~ $ sudo apt-get autoclean
Reading package lists... Done
Building dependency tree
Reading state information... Done
pi@raspberrypi:~ $ sudo yunohost app install https://github.com/tuxmouraille/tvheadend_ynh
Choose a domain for Tvheadend: monDOmaine.com
Choose a path for Tvheadend (default: /tvheadend):
Admin login (default: admin):
Admin password: pass
Warning: gpg: requesting key D401AB61 from hkp server keyserver.ubuntu.com
Warning: gpg: key D401AB61: "Bintray (by JFrog) <bintray@bintray.com>" not changed
Warning: gpg: Total number processed: 1
Warning: gpg:              unchanged: 1
Warning: W: Failed to fetch http://apt.tvheadend.org/unstable/dists/jessie/InRelease  Unable to find expected entry '
Warning:
Warning: E: Some index files failed to download. They have been ignored, or old ones used instead.
Extracting templates from packages: 100%
Success! SSOwat configuration successfully generated
Success! Installation complete
`

**Comment by tuxmouraille** [comment]
OK.
Le problème venait de la présence de l'ancien dépôt: http://apt.tvheadend.org dans le source de apt.
J'étais en train décrire une réponse.
Il n'était utile de réimporter la clé GPG B42317285E12C7CF qui es celle de l'ancien dépôt.
Vérifiez tout de même que celui ci n'est pas toujours configuré:
sudo grep -r apt.tvheadend /etc/apt/source.list*

Pour la clé TNT il faudra peut être à la main activer les dépôts nonfree pour installer les firmware nonfree: firmware-linux-nonfree. A voir avec le doc de Debian.

Tvheadend est très lents pour trouver les multiplex, je préfère donc d'abord faire un scan avec w_scan pour trouver les fréquences.
sudo systemctl stop tvheadend
sudo apt-get install w-scan
sudo w_scan -X -C FR >> /home/admin/channels.conf

**Comment by tuxmouraille** [comment]
Re,
Dans le log, cette ligne indique que le dépôt apt.tvheadend est toujours présent:
Warning: W: Failed to fetch http://apt.tvheadend.org/unstable/dists/jessie/InRelease  Unable to find expected entry '

Cette erreur continuera à apparaître car ce dépôt ne fournit pas de paquet pour ARM.

**Comment by ychoucha** [comment]
Bon premier retour, l'interface à a des problèmes d'affichages, zone transparente : 

![pbinterfacetvheadend](https://cloud.githubusercontent.com/assets/301074/15723032/768bc2c0-2838-11e6-84c8-a1d3b8046ec9.jpg)

ça le fait à pas mal d'endroit

Mais bon ça fonctionne, j'ai bien réussi à scanner mes chaines : 
![tvheadend-raspberry3](https://cloud.githubusercontent.com/assets/301074/15723315/c43b1d30-2839-11e6-8c62-6d8af4882aea.jpg)

le guide des programmes fonctionne : 

![hts tvheadend 4 0 8 jessie - mozilla firefox](https://cloud.githubusercontent.com/assets/301074/15723352/ed22d2e2-2839-11e6-91ee-1dbd450cc453.jpg)


j'ai même réussi à lire mes fichier depuis un Kodi media center : 

![kodi-raspberrylistingchannel](https://cloud.githubusercontent.com/assets/301074/15723402/236bb382-283a-11e6-9c96-efca36fcd144.jpg)

![tvheadend-raspberry3](https://cloud.githubusercontent.com/assets/301074/15723411/298e6a66-283a-11e6-9e8d-8fff1769723f.jpg)
![kodi-raspberry-01](https://cloud.githubusercontent.com/assets/301074/15723413/29b3f3a8-283a-11e6-833d-01ffbd2ed32c.jpg)

pour la clé j'ai installé le formware manuellement --> http://frechdesign.blogspot.fr/2013/11/ubuntu-1310-64-installation-de-la-tv.html


Je peux donc regarder la TV, Tout ça depuis mon raspberry 3 et yunoHost trop bon ça !!
ça a été un peux galére à installé, mon install doit pas être super propre :/

merci à toi pour ton plugin génial :) 

me reste à voir faire marcher le shifting, l'enregistrement de programme
ça c'est une autre histoire :+1:
